### ISSUE TITLE
4k分辨率用d2gl或者d2dx 2倍大小得时候，TP乱飞

### ISSUE THREAD

**Issue by ichunchun** [dabeibao/d2helper#1]
4k分辨率用d2gl或者d2dx 2倍大小得时候，TP乱飞，不跟着鼠标飞。

**Comment by dabeibao** [comment]
哪个版本的d2dx? scale=1有问题吗？

**Comment by ichunchun** [comment]
我今晚试试1倍，加载我直接用的plugy的dllload2=的方法加载的。
乱飞感觉就是例如去a4超市，鼠标指着超市方向，但是人物往上飞

**Comment by dabeibao** [comment]
我用的scale=3,好像没问题。截个屏看看？

**Comment by ichunchun** [comment]
我测试了一下，scale=1，2,3都不行，应该是4k分辨率的问题，因为我win10用的4k分辨率200%显示，感觉是这个问题

**Comment by dabeibao** [comment]
感觉跟这个没关系。不知道是不是加载顺序的问题。我的是3K屏，也是200%显示，

**Comment by dabeibao** [comment]
帮忙试试这个有没有问题？
[Uploading d2helper.zip…]()

**Comment by ichunchun** [comment]
这个可以，谢谢大佬
