### ISSUE TITLE
功能建议，能否像重制版一样，在屏幕上显示设置了快捷键的技能的图标

### ISSUE THREAD

**Issue by jlu511** [dabeibao/d2helper#2]
功能建议，能否像重制版一样，在屏幕上显示设置了快捷键的技能的图标，

**Comment by dabeibao** [comment]
这个对我来说难度有点大了。
另外看了下sgd2, 需要的patch点有点多，感觉很容易和别的插件冲突。
这个插件需要能在各种mod用，现在只用了一个特殊的patch点。

**Comment by jlu511** [comment]
好的，现在主要功能已经很好，慢慢改进，这是非必要功能，哈哈哈，感谢开发这么好的插件

**Comment by dabeibao** [comment]
估计1.13c不支持滚轮事件？这个用autohotkey映射一下？我把滚轮上下滚映射到左右键了。

如果要在界面上能配置，实现起来就麻烦了。

**Comment by jlu511** [comment]
ok.
请问大佬，是否用hack.script，我这边用的时间码头的1.70的d2loader，1.13c，每次在游戏里退出，不是退出到选人画面或者d2标题画面，而是直接退出游戏。是否哪里设置不对。大佬能否分享下你使用的d2loader或者能实现加载hack.script的软件。

**Comment by dabeibao** [comment]
是单机版的吗？单机没用过d2loader. 
以前搞了个单独加载d2hack.script的dll。好久没玩单机去，回头找找还在不在

**Comment by jlu511** [comment]
大佬，是否找到了这个dll，麻烦传到这里，谢谢

**Comment by dabeibao** [comment]
集成到这个插件里了。如果需要单体的，这里说一下。

**Comment by jlu511** [comment]
> 集成到这个插件里了。如果需要单体的，这里说一下。

感谢大佬，单体的也请发一份，方便不同功能dll集成。

**Comment by dabeibao** [comment]
传到最新的版本里了。loadscript.dll

**Comment by jlu511** [comment]
感谢大佬

**Comment by dabeibao** [comment]
短期内实现不了
