### ISSUE TITLE
plugy10.00 似乎与本插件不兼容

### ISSUE THREAD

**Issue by jlu511** [dabeibao/d2helper#4]
插件加载d2hack.script功能似乎与plugy10.00冲突，每次退出游戏时报错c00000005.查看了下，插件加入loadscript.dll功能之前正常，加入loadscript.dll功能之后，d2helper，dll与plugy10.00冲突，换成loadscript.dll依然冲突，确认是loadscript.dll与plugy10.00冲突。之前用plugy14.03，没有问题。因为大箱子整理软件只兼容plugy10.00和hackmap兼容性的问题，最近换成了plugy10.00，发现了这个问题。不知道是否方便修复。修不了也没事，哈哈

**Comment by jlu511** [comment]
错误代码如下：
20:31:23.687  2023-09-18 20:31:23
20:31:23.687  Diablo II running under Windows .Net (Version 6.002)
20:31:23.687  Vendor:  Intel
20:31:23.687  Version: Pentium III (no brand) (Type 0, Family 6, Model C, Stepping 1, Brand 0)
20:31:23.696  Speed: Approx. 2803 MHz
20:31:23.696  Total Physical Memory: 2048.00MB
20:31:23.696  Application Path: D:\Games\Diablo II
20:31:23.696  Local IP: 192.168.43.79
20:31:23.696  Computer name: DESKTOP-QH6UGOL
20:31:23.696  ------------------------------------------------------
20:31:23.696  
20:31:23.696  Missing functions in imagehlp.dll.  Can't generate better stack crawls!
20:31:23.713  BaseMod Installing Patches
20:31:23.713  File BaseMod.mpq not found
20:31:23.713  BaseMod Installing PatchesEx
20:31:23.713  BaseMod Loaded
20:31:23.713  BaseMod Loading: d2helper.dll
20:31:23.870  BaseMod Loading: .\Plugin95\d2hackmap.dll
20:31:23.904  BaseMod Loading: PlugY.dll
20:31:26.860  ........DirectSound progress: Unsupported EAX or EAX emulation
20:31:38.578  
20:31:38.578  
20:31:38.578  ------------------------------------------------------
20:31:38.579  PROGRAM:       Diablo II v1.13
20:31:38.579  TIME:          2023-09-18 20:31:38.578
20:31:38.579  
20:31:38.579  ***** UNHANDLED EXCEPTION: ACCESS_VIOLATION (c0000005)
20:31:38.579  Fault address:  6FD745A0 01:000235A0 D:\Games\Diablo II\D2Common.dll
20:31:38.579  eax:ffffffff ebx:00000067 ecx:fffffffc edx:00000000 esi:08000000
20:31:38.579  edi:23f8200c ebp:00000003 esp:0019f6a4 eip:6fd745a0 flg:00210286
20:31:38.579  cs:0023 ds:002b es:002b ss:002b fs:0053 gs:002b
20:31:38.579  --------------------------------------
20:31:38.579  Thread 3128 ***
20:31:38.579  ----------
20:31:38.579  sShowStack: imagehlp.dll not loaded
20:31:38.579  Stack bytes:
20:31:38.579  0019F6A4: 19000000 FC26E123 20342A23 F348DA6F  ....?? 4*#驢趏
              0019F6B4: 19000000 FC26E123 00000000 50E3DA6F  ....??....P阙o
              0019F6C4: E0A3DD6F 00000000 1B000000 0C180000  啵輔............
              0019F6D4: 68290000 03000000 626F7700 00000000  h)......bow.....
              0019F6E4: 626F7733 0026DE6F 0E060000 00000000  bow3.&辭........
              0019F6F4: 00000000 E0A3DD6F 3FA7DA6F D826DE6F  ....啵輔?иo?辭
              0019F704: 49A7DA6F BED6DA6F 00000000 00000000  Iиo局趏........
              0019F714: 01000000 00000000 48ABDD6F 16000000  ........Ho....
              0019F724: 00000000 00000000 50E3DA6F E0A3DD6F  ........P阙o啵輔
              0019F734: 00000000 00000000 00000000 00000000  ................
              0019F744: 4962DB6F 60F91900 0000AB6F 08040000  Ib踥`?...玱....
              0019F754: 00000000 94F71900 64617461 5C6C6F63  .....?.data\loc
              0019F764: 616C5C66 6F6E745C 4C415449 4E5C6465  al\font\LATIN\de
              0019F774: 6661756C 742E6D61 70001900 00000000  fault.map.......
              0019F784: 98AFF96F 08907123 94AFF96F FFFFFFFF  .o..q#.o
              0019F794: 8C20F56F A920F56F 98AFF96F A3020000  . 鮫?鮫.o?..
              0019F7A4: 30B2F66F 98AFF96F 00000000 5C044C23  0馋o.o....\.L#
              0019F7B4: 10000000 F2937123 3E094C23 07000000  ....?q#>.L#....
              0019F7C4: 258D5000 F2937123 30000000 34084C23  %.P.?q#0...4.L#
              0019F7D4: 01000000 5C044C23 0E947123 00000000  ....\.L#..q#....
              0019F7E4: 7F970110 01000000 60F91900 0000AB6F  .......`?...玱
              0019F7F4: 00000000 01000000 33000000 D7044C23  ........3...?L#
              0019F804: 33000000 1F950110 3B950110 43484900  3.......;...CHI.
              0019F814: 7C006719 64617461 5C6C6F63 616C5C6C  |.g.data\local\l
              0019F824: 6E675C43 48495C42 6173654D 6F642E74  ng\CHI\BaseMod.t
              0019F834: 626C0000 00000000 00000000 00000000  bl..............
              0019F844: 00000000 00000000 00000000 00000000  ................
              0019F854: 00000000 170DAC6F 00000000 00000000  ......琽........
              0019F864: 00000000 60F91900 43484900 AEBEAF6F  ....`?.CHI.痮
              0019F874: B0A54000 BF754000 B8FDBB78 98F81900  哎@.縰@.庚粁.?.
              0019F884: 72C31C77 401C2C02 00000000 00000000  r?w@.,.........
              0019F894: 30086300 00000000 45C2E16F 401C2C02  0.c.....E箩o@.,.
              0019F8A4: 7C72E76F 00000000 59D7E16F 00000000  |r鏾....Y揍o....
              0019F8B4: 00000000 00000000 C87C8F6F 00000000  ........葇.o....
              0019F8C4: 00008000 00D00700 CD7C8F6F 00000000  .....?.蛗.o....
              0019F8D4: 92774000 7CA44000 08A54000 2C784000  .w@.|...,x@.
              0019F8E4: 60F91900 7E366C00 00B03A00 29FD1900  `?.~6l..?.)?.
              0019F8F4: 3CFE1900 01000000 01000000 2F844000  <?........./.@.
              0019F904: 00004000 000D3675 00000000 EC413776  ..@...6u....霢7v
              0019F914: 7E366C00 6034B373 04000000 406CB373  ~6l.`4硈....@l硈
              0019F924: 68E96D00 03000000 30F91900 300FB473  h閙.....0?.0.磗
              0019F934: 903AB373 A038B373 6034B373 E03EB373  .:硈?硈`4硈?硈
              0019F944: 406CB373 1CC0850F FEFFFFFF 74F91900  @l硈.?.?t?.
              0019F954: 00000000 00000000 11000000 01000000  ................
              0019F964: 00000100 00000000 00000000 00000000  ................
              0019F974: 00000000 00000000 00000000 00000000  ................
              0019F984: 00000000 00000000 00000000 00000000  ................
              0019F994: 00000000 00000000 00000000 00000000  ................
              0019F9A4: 00000000 00000000 00000000 00000000  ................
              0019F9B4: 00000000 00000000 00000000 00000000  ................
              0019F9C4: 00000000 00000000 00000000 00000000  ................
              0019F9D4: 00000000 00000000 00000000 00000000  ................
              0019F9E4: 00010000 00000000 00000000 00000000  ................
              0019F9F4: 00000000 00000000 00000000 00000000  ................
              0019FA04: 00000000 00000000 00000000 00000000  ................
              0019FA14: 00000000 00626262 62620000 00000000  .....bbbbb......
              0019FA24: 00000000 00000000 00000000 00000000  ................
              0019FA34: 00000000 00000000 00000000 00000000  ................
              0019FA44: 00000000 00000000 00000000 00000000  ................
              0019FA54: 00000000 00000000 00000000 00000000  ................
              0019FA64: 00000000 00000000 00000000 00000000  ................
              0019FA74: 00000000 00000000 00000000 00000000  ................
              0019FA84: 00000000 00000000 00000000 00000000  ................
              0019FA94: 00000000 00000000 00000000 00000000  ................
              0019FAA4: 00000000 00000000 00000000 00000000  ................
              0019FAB4: 00000000 00000000 00000000 00000000  ................
              0019FAC4: 00000000 00000000 00000000 00000000  ................
              0019FAD4: 00000000 00000000 00000000 00000000  ................
              0019FAE4: 00000000 00000000 00000000 00000000  ................
              0019FAF4: 00000000 00000000 00000000 00000000  ................
              0019FB04: 00000000 00000000 00000000 00000000  ................
              0019FB14: 00000000 00000000 00000000 00000000  ................
              0019FB24: 00000000 00000000 00000000 00000000  ................
              0019FB34: 00000000 00000000 00000000 00000000  ................
              0019FB44: 00000000 00000420 00000000 00000000  ....... ........
              0019FB54: 00000000 00000001 00000000 01000000  ................
              0019FB64: 00040010 00000000 00108140 00010000  ...........@....
              0019FB74: 00000000 00000000 00000000 0010DCF3  ..............荏
              0019FB84: 6F000000 00000000 00000000 00000000  o...............
              0019FB94: 00000000 00000000 00000000 00000000  ................
              0019FBA4: 00000000 00000000 00000000 00000000  ................
              0019FBB4: 00000000 00000000 00000000 00000000  ................
              0019FBC4: 00000000 00000000 00000000 00000000  ................
              0019FBD4: 00000000 00000000 00000000 00000000  ................
              0019FBE4: 00000000 00000000 00000000 00000000  ................
              0019FBF4: 00000000 00000000 00000000 00000000  ................
              0019FC04: 00000000 00000000 00000000 00000000  ................
              0019FC14: 00000000 00000000 00000000 00000000  ................
              0019FC24: 00000000 00000000 00000000 00000000  ................
              0019FC34: 00000000 00000000 00000000 00000000  ................
              0019FC44: 00000000 00000000 00000000 00000000  ................
              0019FC54: 00000000 00000000 00000000 00000000  ................
              0019FC64: 00000000 00000000 00000000 00000000  ................
              0019FC74: 00000000 00000000 00000000 00000000  ................
              0019FC84: 00000000 00000000 00000000 00000000  ................
              0019FC94: 00000000 00000000 00000000 00000000  ................
              0019FCA4: 00000000 00000000 00000000 00000000  ................
              0019FCB4: 00000000 00000101 00000000 00000000  ................
              0019FCC4: 00000000 00000000 00000000 00000000  ................
              0019FCD4: 00000000 00000000 00000000 00000000  ................
              0019FCE4: 00000000 00000000 00000000 00000000  ................
              0019FCF4: 00000000 00000000 00000000 00000000  ................
              0019FD04: 00000000 00000000 00000000 00000000  ................
              0019FD14: 00000000 00000000 00000000 00000000  ................
              0019FD24: 00000000 00AC6D00 D8AA6D00 76312E31  .....琺.鬲m.v1.1
              0019FD34: 33006E00 60FD1900 7353A575 01000000  3.n.`?.sS....
              0019FD44: 4053A575 D8AA6D00 4CA5A575 B0A2A575  @S鬲m.Lゥu阿
              0019FD54: D8AA6D00 F8AB6D00 80FD1900 80FD1900  鬲m.m..?..?.
              0019FD64: DC52A575 CCFD1900 D8AA6D00 8052A575  躌听..鬲m..R
              0019FD74: B9AB1C77 1055A575 90FD1900 94FD1900  公.w.U.?..?.
              0019FD84: E750A575 00000000 8CF8BB78 00000000  鏟.....x....
              0019FD94: E8FD1900 B2B49175 05000000 BF1FDD64  椠..泊.u....?載
              0019FDA4: 00000000 00000000 00000000 662E4000  ............f.@.
              0019FDB4: 1CB04000 00B03A00 08000000 05000000  .癅..?.........
              0019FDC4: 00000000 00000000 00000000 A0FD1900  ............狚..
              0019FDD4: B9AB1C77 60FF1900 20699175 FFA15111  公.w`.. i.u.
              0019FDE4: FEFFFFFF 18FE1900 2CF8BB78 18FE1900  ?.?.,x.?.
              0019FDF4: 20B39175 05000000 000D3675 00000000   ?u......6u....
              0019FE04: 00B03A00 08000000 00000000 00000000  .?.............
              0019FE14: 00000000 70FF1900 CD844000 00000000  ....p..?@.....
              0019FE24: 00000000 3F000F00 000D3675 6C2F4000  ....?.....6ul/@.
              0019FE34: 00000000 00B03A00 70FF1900 80854000  .....?.p....@.
              0019FE44: 14A34000 7E366C00 B2134000 00004000  ..~6l.?@...@.
              0019FE54: 00000000 7E366C00 01000000 94000000  ....~6l.........
              0019FE64: 06000000 02000000 F0230000 02000000  ........?......
              0019FE74: 00000000 00000000 00000000 00000000  ................
              0019FE84: 00000000 00000000 00000000 00000000  ................
              0019FE94: 00000000 00000000 00000000 00000000  ................
              0019FEA4: 00000000 00000000 00000000 00000000  ................
              0019FEB4: 00000000 00000000 00000000 00000000  ................
              0019FEC4: 00000000 00000000 00000000 00000000  ................
              0019FED4: 00000000 00000000 00000000 00000000  ................
              0019FEE4: 00000000 00000000 00000000 46124000  ............F.@.
              0019FEF4: 2E124000 2E124000 00B03A00 44000000  ..@...@..?.D...
              0019FF04: D03C6D00 580B6E00 68746E00 00000000  ?m.X.n.htn.....
              0019FF14: 00000000 00000000 00000000 00000000  ................
              0019FF24: 00000000 00000000 010C0000 01000000  ................
              0019FF34: 00000000 00000000 01000100 00000000  ................
              0019FF44: 00000000 00000000 050000C0 7E366C00  ...........纞6l.
              0019FF54: 00000000 60FE1900 94EA1900 CCFF1900  ....`?..?.?..
              0019FF64: 6C2F4000 30924000 00000000 80FF1900  l/@.0.@........
              0019FF74: C9FC3575 00B03A00 B0FC3575 DCFF1900  牲5u.?.包5u?..
              0019FF84: 1E7B1D77 00B03A00 28FABB78 00000000  .{.w.?.(x....
              0019FF94: 00000000 00B03A00 00000000 00000000  .....?.........
              0019FFA4: 00000000 00000000 00000000 00000000  ................
              0019FFB4: 00000000 00000000 00000000 00000000  ................
              0019FFC4: 8CFF1900 00000000 E4FF1900 E0AD1E77  .......?..喹.w
              0019FFD4: 94CD850F 00000000 ECFF1900 EE7A1D77  .?.....?..顉.w
              0019FFE4: FFFFFFFF CD8A1F77 00000000 00000000  ?.w........
              0019FFF4: 2E124000 00B03A00 00000000 41637478  ..@..?.....Actx
              001A0004: 20000000 01000000 18330000 DC000000   ........3..?..
              001A0014: 00000000 20000000 00000000 14000000  .... ...........
              001A0024: 01000000 07000000 34000000 7C010000  ........4...|...
              001A0034: 01000000 00000000 00000000 00000000  ................
              001A0044: 00000000 00000000 02000000 4EEF261A  ............N?.
              001A0054: 98020000 44000000 E0020000 54020000  ....D...?..T...
              001A0064: 00000000 BA7132F3 34050000 4A000000  ....簈2?...J...
              001A0074: 80050000 42030000 00000000 5B49592D  ....B.......[IY-
              001A0084: C4080000 32000000 F8080000 00030000  ?..2...?......
              001A0094: 00000000 CDEACE32 F80B0000 42000000  ....完??..B...
              001A00A4: 3C0C0000 36030000 00000000 C85F5038  <...6.......萠P8
              001A00B4: 740F0000 5E000000 D40F0000 56030000  t...^...?..V...
              001A00C4: 00000000 440528B1 2C130000 56000000  ....D.(?...V...
              001A00D4: 84130000 98030000 10000000 09000000  ................
              001A00E4: EC000000 02000000 01000000 7C010000  ?..........|...
              001A00F4: D8150000 01000000 02000000 54170000  ?..........T...
              001A0104: A0070000 01000000 03000000 F41E0000  ?..........?..
              001A0114: 8C0E0000 01000000 04000000 802D0000  .............-..
              001A0124: 14030000 02000000 05000000 94300000  .............0..
              001A0134: 98000000 02000000 06000000 2C310000  ............,1..
              001A0144: CC000000 02000000 07000000 F8310000  ?..........?..
              001A0154: F0000000 01000000 09000000 E8320000  ?..........?..
              001A0164: 28000000 02000000 0B000000 10330000  (............3..
              001A0174: 08000000 01000000 53734864 2C000000  ........SsHd,...
              001A0184: 01000000 01000000 01000000 06000000  ................
              001A0194: 8C000000 01000000 A0150000 2C000000  ........?..,...
              001A01A4: 5E000000 5E000000 00000000 00000000  ^...^...........
              001A01B4: 00000000 00000000 00000000 00000000  ................
              001A01C4: 00000000 00000000 00000000 02000000  ................
              001A01D4: 24000000 38000000 00000000 43003A00  $...8.......C.:.
              001A01E4: 5C005700 69006E00 64006F00 77007300  \.W.i.n.d.o.w.s.
              001A01F4: 5C005700 69006E00 53007800 73005C00  \.W.i.n.S.x.s.\.
              001A0204: 00000000 4EEF261A 1C010000 44000000  ....N?.....D...
              001A0214: 64010000 54020000 01000000 BA7132F3  d...T.......簈2?
              001A0224: B8030000 4A000000 04040000 42030000  ?..J.......B...
              001A0234: 02000000 5B49592D 48070000 32000000  ....[IY-H...2...
              001A0244: 7C070000 00030000 03000000 CDEACE32  |...........完?
              001A0254: 7C0A0000 42000000 C00A0000 36030000  |...B...?..6...
              001A0264: 04000000 C85F5038 F80D0000 5E000000  ....萠P8?..^...
              001A0274: 580E0000 56030000 05000000 440528B1  X...V.......D.(?
              001A0284: B0110000 56000000 08120000 98030000  ?..V...........
              001A0294: 06000000 4D006900 63007200 6F007300  ....M.i.c.r.o.s.
              001A02A4: 6F006600 74002E00 57006900 6E006400  o.f.t...W.i.n.d.
              001A02B4: 6F007700 73002E00 53007900 73007400  o.w.s...S.y.s.t.
              001A02C4: 65006D00 43006F00 6D007000 61007400  e.m.C.o.m.p.a.t.
              001A02D4: 69006200 6C006500 00000000 6C000000  i.b.l.e.....l...
              001A02E4: 01000000 06010000 D0010000 02000000  ........?......
              001A02F4: 2C000000 D6020000 2159B07F DDACD501  ,...?..!Y?莠?
              001A0304: 01000000 00000000 00000000 00000000  ................
              001A0314: 00000000 00000000 00000000 01000000  ................
              001A0324: 00000000 00000000 00000000 B2000000  ............?..
              001A0334: 04030000 00000000 00000000 00000000  ................
              001A0344: 00000000 00000000 4D006900 63007200  ........M.i.c.r.
              001A0354: 6F007300 6F006600 74002E00 57006900  o.s.o.f.t...W.i.
              001A0364: 6E006400 6F007700 73002E00 53007900  n.d.o.w.s...S.y.
              001A0374: 73007400 65006D00 43006F00 6D007000  s.t.e.m.C.o.m.p.
              001A0384: 61007400 69006200 6C006500 2C007000  a.t.i.b.l.e.,.p.
              001A0394: 72006F00 63006500 73007300 6F007200  r.o.c.e.s.s.o.r.
              001A03A4: 41007200 63006800 69007400 65006300  A.r.c.h.i.t.e.c.
              001A03B4: 74007500 72006500 3D002200 78003800  t.u.r.e.=.".x.8.
              001A03C4: 36002200 2C007000 75006200 6C006900  6.".,.p.u.b.l.i.
              001A03D4: 63004B00 65007900 54006F00 6B006500  c.K.e.y.T.o.k.e.
              001A03E4: 6E003D00 22003600 35003900 35006200  n.=.".6.5.9.5.b.
              001A03F4: 36003400 31003400 34006300 63006600  6.4.1.4.4.c.c.f.
              001A0404: 31006400 66002200 2C007400 79007000  1.d.f.".,.t.y.p.
              001A0414: 65003D00 22007700 69006E00 33003200  e.=.".w.i.n.3.2.
              001A0424: 22002C00 76006500 72007300 69006F00  ".,.v.e.r.s.i.o.
              001A0434: 6E003D00 22003600 2E003000 2E003100  n.=.".6...0...1.
              001A0444: 39003000 34003100 2E003100 22005300  9.0.4.1...1.".S.
              001A0454: 79007300 74006500 6D002000 44006500  y.s.t.e.m. .D.e.
              001A0464: 66006100 75006C00 74002000 43006F00  f.a.u.l.t. .C.o.
              001A0474: 6E007400 65007800 74000000 78003800  n.t.e.x.t...x.8.
              001A0484: 36005F00 6D006900 63007200 6F007300  6._.m.i.c.r.o.s.
              001A0494: 6F006600 74002E00 77006900 6E006400  o.f.t...w.i.n.d.
              001A04A4: 6F007700 73002E00 73007900 73007400  o.w.s...s.y.s.t.
              001A04B4: 65006D00 63006F00 6D007000 61007400  e.m.c.o.m.p.a.t.
              001A04C4: 69006200 6C006500 5F003600 35003900  i.b.l.e._.6.5.9.
              001A04D4: 35006200 36003400 31003400 34006300  5.b.6.4.1.4.4.c.
              001A04E4: 63006600 31006400 66005F00 36002E00  c.f.1.d.f._.6...
              001A04F4: 30002E00 31003900 30003400 31002E00  0...1.9.0.4.1...
              001A0504: 31005F00 6E006F00 6E006500 5F003000  1._.n.o.n.e._.0.
              001A0514: 34003900 66003500 64006400 38003100  4.9.f.5.d.d.8.1.
              001A0524: 37003900 37006600 34006600 39000000  7.9.7.f.4.f.9...
              001A0534: 4D006900 63007200 6F007300 6F006600  M.i.c.r.o.s.o.f.
              001A0544: 74002E00 57006900 6E006400 6F007700  t...W.i.n.d.o.w.
              001A0554: 73002E00 49007300 6F006C00 61007400  s...I.s.o.l.a.t.
              001A0564: 69006F00 6E004100 75007400 6F006D00  i.o.n.A.u.t.o.m.
              001A0574: 61007400 69006F00 6E000000 6C000000  a.t.i.o.n...l...
              001A0584: 00000000 10010000 70040000 02000000  ........p.......
              001A0594: 06010000 80050000 2E74737C B5BAD701  .........ts|岛?
              001A05A4: 01000000 00000000 00000000 00000000  ................
              001A05B4: 00000000 00000000 00000000 01000000  ................
              001A05C4: 00000000 00000000 00000000 BC000000  ............?..
              001A05D4: 88060000 00000000 00000000 00000000  ................
              001A05E4: 00000000 00000000 4D006900 63007200  ........M.i.c.r.
              001A05F4: 6F007300 6F006600 74002E00 57006900  o.s.o.f.t...W.i.
              001A0604: 6E006400 6F007700 73002E00 49007300  n.d.o.w.s...I.s.
              001A0614: 6F006C00 61007400 69006F00 6E004100  o.l.a.t.i.o.n.A.
              001A0624: 75007400 6F006D00 61007400 69006F00  u.t.o.m.a.t.i.o.
              001A0634: 6E002C00 70007200 6F006300 65007300  n.,.p.r.o.c.e.s.
              001A0644: 73006F00 72004100 72006300 68006900  s.o.r.A.r.c.h.i.
              001A0654: 74006500 63007400 75007200 65003D00  t.e.c.t.u.r.e.=.
              001A0664: 22007800 38003600 22002C00 70007500  ".x.8.6.".,.p.u.
              001A0674: 62006C00 69006300 4B006500 79005400  b.l.i.c.K.e.y.T.
              001A0684: 6F006B00 65006E00 3D002200 36003500  o.k.e.n.=.".6.5.
              001A0694: 39003500 62003600 34003100 34003400  9.5.b.6.4.1.4.4.
20:31:38.579  Code bytes:
20:31:38.579  6FD745A0: 8B048F5B 5F23C65E C208005B 5F33C05E  ...[_#芧?.[_3繼
              6FD745B0: C2080033 C05EC208 00CCCCCC CCCCCCCC  ?.3繼?.烫烫烫?

**Comment by dabeibao** [comment]
这个得看看d2hack.script修改的是不是和plugy 10.0冲突了。loadscript自己不改内存。

**Comment by jlu511** [comment]
> 这个得看看d2hack.script修改的是不是和plugy 10.0冲突了。loadscript自己不改内存。

好的，我尝试了下 确实是脚本的问题，用了16k save，是这个冲突，禁用了就好了
