### ISSUE TITLE
小请求

### ISSUE THREAD

**Issue by jlu511** [dabeibao/d2helper#5]
大佬，网上找到个破免板子代码，据说需要写成dll，身边朋友没有会的，大佬能在百忙之中，给弄成dll吗，如果没时间也不要紧？据说是根据人物身上的属性，判断怪物身上有同类免疫，就改为抗性99.
	//破免板子功能	{D2DLL_D2GAME,0xDB3E0,(DWORD)PATCH_JMP,FALSE,0x01},	{D2DLL_D2GAME,0xDB3E0,(DWORD)Pierce_FixAsm,TRUE,0x00},		const uint32_t D2GAME_PIERCE_DLLBASE1 = (DLLBASE_D2GAME + 0xDB3EC);const uint32_t D2GAME_PIERCE_DLLBASE2 = (DLLBASE_D2GAME + 0xDB3E5);const uint32_t D2GAME_PIERCE_DLLBASE3 = (DLLBASE_D2GAME + 0xDB3f8);int __stdcall  Pierce_DIY(UnitAny* pPlayer, int resItemStatCostNo){	if (!pPlayer) return 0;	if (pPlayer->dwType != 0) return 0;	int GetPlayerPierceFixIscNo=0;	switch (resItemStatCostNo)	{	case 39:		GetPlayerPierceFixIscNo = Config.PassiveFireOpenIsc;		break;	case 41:		GetPlayerPierceFixIscNo = Config.PassiveLtngOpenIsc;		break;	case 43:		GetPlayerPierceFixIscNo = Config.PassiveColdOpenIsc;		break;	case 45:		GetPlayerPierceFixIscNo = Config.PassivePoisOpenIsc;		break;	case 37:		GetPlayerPierceFixIscNo = Config.PassiveMagOpenIsc;		break;	case 36:		GetPlayerPierceFixIscNo = Config.PassiveDmgOpenIsc;		break;	default:		break;	}	return D2COMMON_GetUnitStat(pPlayer, GetPlayerPierceFixIscNo, 0);}int __stdcall  PierceNum_DIY(UnitAny* pPlayer, int isc){	if (!pPlayer) return 0;	if (pPlayer->dwType != 0) return 0;	int JianKang = D2COMMON_GetUnitStat(pPlayer, isc, 0);	JianKang = JianKang >= 50 ? 50 : JianKang;	return JianKang;}__declspec (naked) void __stdcall Pierce_FixAsm(){	__asm	{		cmp esi, 99		jle __PierceYes		push[esp - 0x8]		push[esp + 0x24]		call Pierce_DIY		test eax, eax		jnz __PierceYes1		jmp D2GAME_PIERCE_DLLBASE2		__PierceYes :		jmp D2GAME_PIERCE_DLLBASE1			//破免之后			__PierceYes1 :		mov esi, 95							//设定怪物抗性95			push dword ptr ds : [ebx + 0xc]			push[esp + 0x24]			call PierceNum_DIY					//设定最大减抗50			jmp D2GAME_PIERCE_DLLBASE3	}}

**Comment by dabeibao** [comment]
这个倒是挺容易的，但这个代码不全啊，跟我用的模板差别比较大，，

**Comment by jlu511** [comment]
啊，不会吧

**Comment by dabeibao** [comment]
是关键代码。剩下的模板我这没有，，，
