### ISSUE TITLE
加载d2hack.script

### ISSUE THREAD

**Issue by blackdarks** [dabeibao/d2helper#6]
需要加载loadscript这个dll吗？还是只要放在helper同目录就行？

**Comment by blackdarks** [comment]
如果要和夜妖风的插件共用怎么设置？？我看d2ext.ini同命容易覆盖

**Comment by dabeibao** [comment]
loadscript是给不需要快捷施法的人用的。如果有d2helper就用不着loadscript了。

夜妖风的插件已经包含了d2helper的快捷施法了。如果有夜妖风的插件，也不需要d2helper了。

**Comment by blackdarks** [comment]
主要是想使用helper的加载hack.script这个功能，但是好像发现设置true了没有效果

**Comment by dabeibao** [comment]
如果是夜妖风的，用plugy加载一下loadscript.dll就行了。
d2helper.dll和夜妖风的插件用的同一个patch点，会冲突

**Comment by blackdarks** [comment]
然后就在夜妖风的那个插件D2EXT.ini里加上file=XXX.script就行了吗？

**Comment by dabeibao** [comment]
如果要在夜妖风的mod加载d2hack.script, 得用plugy加载那个loadscript.dll。夜妖风的mod没有加载.script的功能
